### ISSUE TITLE
Sqlite Browser ships old version SQLite 

### ISSUE THREAD

**Issue by KristijanZic** [flathub/org.sqlitebrowser.sqlitebrowser#3]
The SQLite that this flatpak is shipping is more than a year old now and there have been quite a few new features added in that time and some critical security fixes too.
Could SQLite be updated to the latest version? [https://www.sqlite.org/changes.html](https://www.sqlite.org/changes.html )

**Comment by Mailaender** [comment]
It is part of the [FreeDesktop SDK](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) which has a release expected to be around this month.
